### ISSUE TITLE
add Torie (others?) to netlify CMS editor

### ISSUE THREAD

**Issue by 7yl4r** [marinebon/www_marinebon2#1]
Hi @bbest : Can you make sure Torie ( @torieketcham torie.ketcham@noaa.gov ) is in the list of editors allowed to use the CMS at https://marinebon2.netlify.app/admin ? 

Also: are there others we should add?

**Comment by bbest** [comment]
Thanks @7yl4r! @torieketcham, invitation was sent from Netlify.

![image](https://user-images.githubusercontent.com/2837257/111710464-fc5bfb80-8806-11eb-8434-3c0cf98ca07c.png)

**Comment by bbest** [comment]
@7yl4r, we're only allowed 5 free invitations, so let's find out from Torie, Gabrielle and Frank who else we should add.

**Comment by bbest** [comment]
More on this from...

https://wowchemy.com/docs/getting-started/cms/#3-invite-editors

## 3. Invite editors

Head to the _Identity_ tab at the _top_ of the Netlify dashboard and then click the _Invite Users_ button.

![image](https://user-images.githubusercontent.com/2837257/111710623-447b1e00-8807-11eb-8844-4f5713df3bc3.png)

Invite yourself and any collaborators to become editors.

**Comment by bbest** [comment]
This worked:

> Hi Torie,
> 
> Can you please try the following steps:
> 
> Accept the invitation sent to you by finding the email:
>   
>   TO: torie.ketcham@noaa.gov
>   FROM: no-reply@netlify.com
>   DATE: March 18, 2021
>   SUBJECT: You've been invited to join pedantic-spence-f73fef.netlify.appInbox
>   
>   and clicking on Accept the invite
> 
> Visit and log into [marinebon2.netlify.app/admin](http://marinebon2.netlify.app/admin).
