### ISSUE TITLE
Issue adding images

### ISSUE THREAD

**Issue by torieketcham** [marinebon/www_marinebon2#10]
I'm trying to add an image to the homepage via a blank widget which I've called "[Intro-image](https://marinebon2.netlify.app/admin/#/collections/home/entries/intro-image)". It doesn't show up on the site, even though you can see it [here](https://github.com/marinebon/www_marinebon2/blob/master/static/media/mbon_goos_framework.png) Is there something I am missing?

**Comment by 7yl4r** [comment]
Hmm. Hard to see what is going on here.

The files seem to be in the correct place, and the widget is showing up on the page:

![image](https://user-images.githubusercontent.com/1051390/115743820-04580f80-a360-11eb-8abd-0b8e1d5dada3.png)

The problem is that the image is not found at the address it is expected (https://marinebon2.netlify.app/static/media/mbon_goos_framework.png). The image is actually being served at https://marinebon2.netlify.app/media/mbon_goos_framework.png. I'm not sure why the `/static/` is getting removed. For some reason the CMS is assuming one url when uploading the image and another url when looking for it. I don't see anything in the .toml files to explain this.

Need to do some more looking.

**Comment by 7yl4r** [comment]
Looking at this again now.

It looks like the relevant config options for the netlify CMS should be in `/admin/config.yml` ([config options docs](https://www.netlifycms.org/docs/configuration-options/)).
We don't have that file in this repo.
We don't even have an `/admin/` dir.
The values must be inheriting from the academic template, the wowchemy base code, or else defaults are being used by hugo.
I think we can create a `/admin/config.yml` in this repo to override those settings but I want to find where the issue stems from first.

* wowchemy/starter-academic doesn't have an `/admin/` dir. There is a [`/config/_default/config.yaml`](https://github.com/wowchemy/starter-academic/blob/master/config/_default/config.yaml) file, but that is something different - hugo config I think.
* a search of wowchemy/wowchemy-hugo-modules doesn't turn up a relevant `config.yaml` either. After some more creative searching I did find [/wowchemy-cms/data/wowchemy_cms_tpl.yaml](https://github.com/wowchemy/wowchemy-hugo-modules/blob/main/wowchemy-cms/data/wowchemy_cms_tpl.yaml), which looks like a template of the netlify config file. I can't confirm that without digging deeper into how wowchemy, netlify, & hugo work. It looks like that file might be getting injected [here](https://github.com/wowchemy/wowchemy-hugo-modules/blob/0afcc81296debb841d33af33ebe89353df0f14d6/wowchemy-cms/functions/parse.html#L2-L4), but how that works is unclear at this time. The netlify config docs specify that a custom url can be used along with a link tag and `rel="cms-config-url"`; weirdly: a search for `cms-config-url` turns up nothing - however this works is confusing.

**Comment by 7yl4r** [comment]
Created a new homepage widget to reproduce the error with new config.yml in place.
Exact same result, as expected.

I am still not understanding what is happening here. 
Images are going into `static/media` but I think `/admin/config.yml` says they should go to `/static/media` - that directory DNE.
The change to `/admin/config.yml` might not have any affect at all - in fact I think it would be throwing errors if it were being used b/c of the handlebars (`{{ }}`) in there.

**Comment by 7yl4r** [comment]
The only relevant search result from the academic template for `static` is [this section of `init_kickstart.sh`](https://github.com/wowchemy/starter-academic/blob/8ab10905ebb5ba7da615f73f6b1558f265e37a1c/scripts/init_kickstart.sh#L15-L16). 
I don't know how that file gets used; a search for `init_kickstart` returned no results.

**Comment by 7yl4r** [comment]
did another test of adding an image widget.
The issue persists.

I need to revisit and dig deeper into where the netlify config is coming from.
The `/admin/config.yml` file is being ignored and that is unexpected.

@bbest : have you used wowchemy/netlify for another site? 
I am having a lot of trouble setting netlify's configuration options and I don't understand where the netlify configuration options are coming from for this repository.

**Comment by 7yl4r** [comment]
@bbest and I debugging more now:

* wowchemy updated to latest using `update_wowchemy.sh`.
    * new version of wowchemy build checks for broken links and throws errors (this is good)
* possibly relevant detail: prior to wowchemy v5.1 the dir was `/static/media` and now it is `/assets/media`
* it seems like the netlify-cms wowchemy module is using the old way of dealing with media paths but the build system is using the new way. Is it possible we have updated one module but not the other?
* go dependencies are tracked in the `go.mod` and `go.sum` files. These were updated by the `update_wowchemy.sh` script and the content looks reasonable when comparing to the latest from starter-academic.

Gonna take a break from this then come back.
Tentative plan for moving forward is to find a workaround for getting images onto the homepage - possibly without using the widgets.

**Comment by bbest** [comment]
Since migrating all `static/media` instances to `assets/media`, the [/admin](https://marinebon2.netlify.app/admin) interface will properly upload imagery into [`/assets/media/`](https://github.com/marinebon/www_marinebon2/tree/master/assets/media) and browse for selection there, but creating a new homepage entry image requires manually stripping off the excess prefix:

## FAIL

```yaml
image: /assets/media/mbon_goos_framework.png
```

## SUCCESS

```yaml
image: mbon_goos_framework.png
```

For instance, see difference in commit https://github.com/marinebon/www_marinebon2/commit/676b48dac5dd6601f94a328e9572ac75f61d7802.

**Comment by bbest** [comment]
Here's a bit more background.

If the `image` path isn't set right, the problems show up in the Netlify Deplyoys (https://app.netlify.com/sites/marinebon2/deploys) like so:

```
4:20:00 PM: ────────────────────────────────────────────────────────────────
4:20:00 PM:   1. build.command from netlify.toml                            
4:20:00 PM: ────────────────────────────────────────────────────────────────
4:20:00 PM: ​
4:20:00 PM: $ hugo --gc --minify -b $URL
4:20:02 PM: hugo: collected modules in 1735 ms
4:20:02 PM: Start building sites …
4:20:03 PM: ERROR 2021/05/03 23:20:02 Couldn't find `/static/media/intro_image_test2.png` in the `assets/media/` folder - please add it.
ERROR 2021/05/03 23:20:03 Couldn't find `/static/media/intro_image_test3.png` in the `assets/media/` folder - please add it.
ERROR 2021/05/03 23:20:03 Couldn't find `https://marinebon2.netlify.app/media/intro_image_test2.png` in the `assets/media/` folder - please add it.
```

## References

- [Media and Public Folders -- Configuration Options | Netlify CMS | Open-Source Content Management System](https://www.netlifycms.org/docs/configuration-options/#media-and-public-folders)
- [Media and Public Folder -- Beta Features! | Netlify CMS | Open-Source Content Management System](https://www.netlifycms.org/docs/beta-features/#folder-collections-media-and-public-folder)
- [wowchemy-hugo-modules:wowchemy-cms/data/wowchemy_cms_tpl.yaml#L5-6](https://github.com/wowchemy/wowchemy-hugo-modules/blob/main/wowchemy-cms/data/wowchemy_cms_tpl.yaml#L5-L6)

**Comment by 7yl4r** [comment]
@torieketcham : 
Take a look at the images added to the homepage. 
The full-width one that scrolls weirdly is the default behavior of the widget as you were trying to use it. 
If we want that behavior we can make it happen but I think your intention was probably different for this image. 

I just added a section for the image in a different way and I think it better matches your intention.
I think adding th

1. add an image
    1. "media" (top left)
    2. upload
2. create new homepage widget section
    1. "contents" (top left)
    2. "new homepage"
    3. "body" (at bottom)
    4. "+"
    5. "image"
    6. "choose image" 
    7. flip switch from "rich text" to "markdown"
    8. modify the url in the markdown image tag from `![](/assets/media/mbon_goos_framework.png)` to `![](https://marinebon2.netlify.app/media/mbon_goos_framework.png)`
    9. ⚠️ ...uh oh. Things still don't work. The url isn't valid for some reason. Why does `https://marinebon2.netlify.app/media/intro_image_test4-bb.png` work but `https://marinebon2.netlify.app/assets/media/mbon_goos_framework.png` does not? Weird.

...So I guess this doesn't work right now.

**Comment by torieketcham** [comment]
Hi @7yl4r - yes, I was going to ask you both about removing that parallax effect on the image. I had tried moving the image to the body section too, with no luck.

**Comment by bbest** [comment]
Hey @7yl4r,

Unfortunately this commit [∆ test label in netlify cms · marinebon/www_marinebon3@ff672f4](https://github.com/marinebon/www_marinebon3/commit/ff672f40de0f409fa63316c8652ab87c7ebc9f87) and visiting [marinebon3.netlify.app/admin](https://marinebon3.netlify.app/admin) demonstrated that copying from [wowchemy/wowchemy-hugo-modules: data/wowchemy_cms_tpl.yaml](https://github.com/wowchemy/wowchemy-hugo-modules/blob/2d9c18ecf0ef268ccc9f3688a06cc83217344d30/wowchemy-cms/data/wowchemy_cms_tpl.yaml) into [admin/config.yml](https://github.com/marinebon/www_marinebon3/blob/master/admin/config.yml) does not allow us to tweak the Netlify CMS interface to fix this issue.

Other possibilities:
- Rename admin/config.yml to config.yaml (probably not going to make a difference)
- Fork [wowchemy/wowchemy-hugo-modules](https://github.com/wowchemy/wowchemy-hugo-modules) into marinebon, edit [wowchemy-cms/data/wowchemy_cms_tpl.yaml](https://github.com/wowchemy/wowchemy-hugo-modules/blob/main/wowchemy-cms/data/wowchemy_cms_tpl.yaml) and update our own [marinebon/www_marinebon3: config.yaml](
https://github.com/marinebon/www_marinebon3/blob/c3a35bc841d1e078ea1d18ba466ae5824c06d1e2/config.yaml#L26) like so:
  
  ```yaml
  module:
  imports:
    - path: github.com/marinebon/wowchemy-hugo-modules/wowchemy-cms
  ```

**Comment by torieketcham** [comment]
@bbest @7yl4r just checking back in with this. Can you let me know how I should be adding images for the homepage (and subpages) - or are we still working through the issue?

**Comment by 7yl4r** [comment]
We are still working on this. I am feeling stuck on it. @bbest : do you have more ideas?

**Comment by torieketcham** [comment]
Do you think I should continue to work on other aspects of the site (right now I am adding publications, which have their own minor challenges, although they don't seem to be insurmountable)? I'm just wary of expending a lot of effort if our determination is that we should move forward with a different solution.

**Comment by 7yl4r** [comment]
It's fixed.

I don't exactly know how but part of our issue was putting the CMS config at `/admin/config.yml` but it should have been at `/content/admin/config.yml`. 

Let's leave this issue open until we finish ironing this out and cleaning up our testing messes.

1. [ ] figure out how to insert images with better formatting (try inserting images in the text box?)
2. [ ] delete test images
3. [ ] delete test "Homepage" widgets
4. [ ] read through new `/content/admin/config.yml` to be sure all is as it should be (rm `-TEST` stuff I added)
5. [ ] determine the fate of marinebon/www_marinebon3
6. [ ] read through commit history to check for any other tmp debug things we changed

**Comment by torieketcham** [comment]
Does this mean that adding new images to the /assets/media folder (for example arms_mbon.png) will work? I tried to do so on a news article but without success.

**Comment by torieketcham** [comment]
I solved the problem on that page by uploading the image directly within the Netlify interface rather than trying to link to an existing image URL. It looks like it's set up so that images for a given section (posts, products etc) will go in that particular folder.

**Comment by torieketcham** [comment]
As a follow-on to this, I attempted to add an image to [this page](https://marinebon2.netlify.app/about/description/), both with markdown and using the prose.io interface, and nothing is showing up. So I am not sure how to make this work.

**Comment by torieketcham** [comment]
I'm bypassing Wowchemy templates completely and just using a blank widget with markup for the intro on the homepage, but still running into trouble with images. Any way you could take another look at this?

**Comment by 7yl4r** [comment]
I just posted a discussion to the wowchemy folks [here](https://github.com/wowchemy/wowchemy-hugo-modules/discussions/2334). Hopefully some fresh eyes on the problem will help because this seemingly simple problem has fried my brain.

**Comment by 7yl4r** [comment]
Here is a possible workaround:

1. manually images in `/static/` so they are served without hugo checking urls ([ref](https://gohugo.io/content-management/static-files/)).
2. link to the images in markdown as `![my image alt text](/static/img/post2/whatever.png)`.

**Comment by torieketcham** [comment]
Interestingly, while your above recommendation does not appear to work, the image is now showing up as mbon_goos_framework.png (i.e. without anything else in the image path), which it was not doing until just now (I've had it up there for several days and it was displaying as a broken link).

**Comment by torieketcham** [comment]
As additional context:

https://marinebon2.netlify.app/static/img/post2/mbon_goos_framework.png - does not work

https://marinebon2.netlify.app/assets/media/mbon_goos_framework.png - does not work

https://marinebon2.netlify.app/mbon_goos_framework.png - now works (but didn't before?)

**Comment by 7yl4r** [comment]
Okay. Some small surprises here but we can work with it:

> https://marinebon2.netlify.app/static/img/post2/mbon_goos_framework.png - does not work

This would work if the image was moved into a directory `/static/static/img/post2/`. 

> https://marinebon2.netlify.app/assets/media/mbon_goos_framework.png - does not work

This is the one that should work using the `media_folder` but isn't. 

> https://marinebon2.netlify.app/mbon_goos_framework.png - now works (but didn't before?)

This means stuff in `/static/` get put onto the domain directly.

-----------------------------

Here is what I think we should do (assuming it will work):

1. create directory `/static/media_content/`
2. create directories inside `/static/media_content/` as needed to match `/content/` subdirectories
2. put images in `/static/` location corresponding to the page using them in `/content/`
3. link to the images using raw markdown like `![alt txt](/media_content/{img_path}.png)`

Example for `mbon_goos_framework.png` on the homepage.

1. create directory `/static/media_content/home/` to match `/content/home/`
2. upload file `intro-image_mbon_goos_framework.png` into `/static/media_content/home/` (NOTE: I prefixed the filename with the name of the `.md` using it)
3. edit `intro-image.md` to use the image like `![mbon goos framework](/media_content/home/intro-image_mbon_goos_framework.png)`

Thoughts?

**Comment by torieketcham** [comment]
That works! I've added an image [here](https://marinebon2.netlify.app/about/description/) as well, using your recommendation, and it's showing up too.

**Comment by 7yl4r** [comment]
Seems like we have figured out a workable workflow for this so I will close in spite of us being unable to make things work as they should.
