### ISSUE TITLE
google analytics setup

### ISSUE THREAD

**Issue by 7yl4r** [marinebon/www_marinebon2#12]
setup for google analytics should be as simple as pasting the relevant info into the following lines:

https://github.com/marinebon/www_marinebon2/blob/master/config/_default/params.toml#L290-L292

```
  google_analytics = ""
  google_tag_manager = ""
  google_site_verification = ""
```

**Comment by torieketcham** [comment]
I've added the tag so we should be all set here. I'll check GA in a bit to see if we're receiving any data.
