### ISSUE TITLE
Removing bottom "card" from news articles etc

### ISSUE THREAD

**Issue by torieketcham** [marinebon/www_marinebon2#17]
Hey @7yl4r - could you help me figure out how to remove the following bottom cards (social/author) from news articles on the site? I tried poking around in some of the files, but am worried I might break something...

<img width="1365" alt="Screen Shot 2021-05-28 at 11 24 25 AM" src="https://user-images.githubusercontent.com/44508950/120008083-9a5b0780-bfa8-11eb-85ae-14fc650ef785.png">

**Comment by 7yl4r** [comment]
This should be easy to fix but I can't get to it for a week maybe two.

**Comment by torieketcham** [comment]
Never mind, I figured out how to remove it. Closing this issue.

**Comment by 7yl4r** [comment]
nice! :+1:
