### ISSUE TITLE
simplify About Us sections

### ISSUE THREAD

**Issue by 7yl4r** [marinebon/www_marinebon2#28]
merge 1st 4 about us nav sections into 1

**Comment by torieketcham** [comment]
Hi @7yl4r - I'm trying to update the About section and running into some issues... I can't make the "About" link an actual link - it doesn't seem to allow me to do so. Is there something in the wowchemy code that is forcing that menu item not to be an actual link?

**Comment by 7yl4r** [comment]
Yes, I suspect that a dropdown parent cannot be a link too. 

I could try to modify [`www_marinebon2/layouts/partials/navbar.html`](https://github.com/marinebon/www_marinebon2/blob/master/layouts/partials/navbar.html) so that will work but maybe we can just make the menu like:

* About 
    * About MBON
    * Timeline
    * People
    * ...
* The Network
    * ...
* ... 

Where the "About MBON" acts as the top level link

**Comment by torieketcham** [comment]
Okay, I've done that.
