### ISSUE TITLE
Product Gallery

### ISSUE THREAD

**Issue by 7yl4r** [marinebon/www_marinebon2#4]
Putting some notes here to help me keep track of the ongoing "product gallery" discussion. 

The basic idea is to have a page which highlights work like infographiq, early alert dashboards, etc.

I made the following mockup:

![MBON-product-gallery-mockup](https://user-images.githubusercontent.com/1051390/113595901-9a253800-9607-11eb-8229-7f7e74939d3a.png)

Ben built a prototype technical product showcase here: https://marinebon.org/products/

**Comment by 7yl4r** [comment]
I met with Stephen Richard from the EarthCube resource registry & USGIN to discuss potential synergy with EarthCube's efforts to catalog tools & tool metadata. My dream would be to register our tools with the EarthCube registry and then create a pretty view using their backend or some RESTful frontend they would provide. 

Regarding registering: we should probably do that anyway. Here is the [EarthCube Tool Registry Form](https://docs.google.com/forms/d/e/1FAIpQLSfqyga5GGjKNB9CeQjO0kdIDaQ38A5nINXwBc-lmTTozMmP3w/viewform). Stephen was able to look at the seascapeR package and add it relatively easily. The resulting record can be viewed in the [Suave tool browser interface](https://suave2.sdsc.edu/main/file=zaslavsk_EC_Resource_Registry.csv), just search for "seascape". After another harvesting/processing step is complete the record will be viewable in the [GEOCODES tool browser](https://beta.geocodes.earthcube.org/landing.html). This tool browser will soon be upgraded to something like the [new GEOCODES interface (currently beta)](https://beta.geocodes.earthcube.org/landing.html).

My quick notes about way this all works:

1. registry form goes to spreadsheet
2. data gets picked up and turned into JSON-LD (based on Schema.org?).
3. data is put into a triplestore database so SPARQL queries can be run
4. other harvesters (like google datasets) can pick up the data published as JSON-LD using schema.org standards.

**Comment by bbest** [comment]
---------- Forwarded message ---------
From: Ben Best <ben@ecoquants.com>
Date: Mon, Jun 14, 2021 at 10:11 AM
Subject: Re: Organizing some MBON products

Hi Frank, Matt and all,
Similar to the Project tiles on [ioos.us](ioos.us):

![image](https://user-images.githubusercontent.com/2837257/122255928-73934100-ce83-11eb-890a-de3418a45d74.png)

I started to create some Bootstrap cards of MBON Products here:

[marinebon.org/products](https://marinebon.org/products) ([source](https://github.com/marinebon/products)) 
![image](https://user-images.githubusercontent.com/2837257/122256111-97568700-ce83-11eb-918b-eb6af1e3d82f.png)

Tylar, Torrie and I are working on an update to the marinebon.org website here:

[marinebon2.netlify.app](https://marinebon2.netlify.app/) ([source](https://github.com/marinebon/www_marinebon2))
This will feature a Products section similar to other Wowchemy sites like here:

[BrombergLab](https://bromberglab.org/)
![image](https://user-images.githubusercontent.com/2837257/122256317-cb31ac80-ce83-11eb-911f-7d84a903a194.png)
 
Notice how Projects above could be similar to MBON Products. We can have tags like eDNA, Seascapes or Infographics that can be clicked on above the MBON Product cards to filter accordingly. Clicking on any one MBON Product would then open its own dedicated page for more details.

We could populate these MBON Products with a Google Sheet as Matt suggests. Part of the reason we're experimenting with Wowchemy is that it provides a [free editing interface](https://wowchemy.com/docs/getting-started/cms/) to add and edit such content.

Jenn's slide showing the various locations of infographic resources, both the core building materials (i.e. marinebon/infographiqJS, infographiqR and infographiq) as well as instances grouped by owner (e.g. noaa-iea/fk-esr-info, noaa-onms/cinms, ioos/sanctsound), would be good material for the detail page of the Infographic MBON Product.
Comments are most welcome.

Thanks, Ben

**Comment by 7yl4r** [comment]
Steps to set this up using the same "projects" system:

* [ ] override hugo config.yml
* [ ] add "products" collection
* [ ] add items to `/content/products/`
* [ ] set up products summary page

**Comment by 7yl4r** [comment]
Some notes about how it works (top-down starting from main page content):

1. .md file defines page content and includes a widget
2. widget is rendered using the html template
3. html template grabs all .md files in the folder for a specfic archetype (or collection?)
4. layout .html describes how to render the archetype data

-------------------------

Also worth noting here: There are four different views that might be rendered to summarize the content [ref](https://github.com/wowchemy/wowchemy-hugo-modules/blob/19ca4a39f23c20d47ff05232bd2a577e945ede4b/wowchemy/layouts/partials/widgets/portfolio.html#L65-L73).
I think we want to use the "card" but I am not sure what the others look like. I don't know what view is being rendered for "projects" now but it doesn't look like the card view shown on the hugo-academic demo site.

**Comment by 7yl4r** [comment]
The product view is now working.
I am surprised because I didn't think I was done setting things up but I am not fixing what ain't broke.

We are now ready to discuss
1. what tools and data products should be included
2. what tags should use use (& highlight) to organize these

## regarding what to include:

There are many lists to pull from here, including:

1. the list emailed out by Joana(?) long ago
2. [this infographiq doc page](https://marinebon.org/infographiq/organization-of-infographiq-components.html) listing infographics

## regarding tags:

1. data product / tool / tool usage instance
2. regional mbon association(s)
3. thematic mbon association(s)

**Comment by 7yl4r** [comment]
* one page for seascape tools:
    * joaqin's seascape viewer
    * seascapR
* axiom MBON
* other dashboards
* all infographics from above link
* others from FMK's report

**Comment by bbest** [comment]
Aw yeah, well done @7yl4r 🥳 

<img width="1173" alt="Screen Shot 2021-07-30 at 5 54 18 PM" src="https://user-images.githubusercontent.com/2837257/127686338-5ac300b9-2954-4e73-99d3-be37b85d56a3.png">

**Comment by MathewBiddle** [comment]
Ran across this the other day: https://sbc.marinebon.org/data/

**Comment by 7yl4r** [comment]
> Ran across this the other day: https://sbc.marinebon.org/data/

Looks like we aren't the only one thinking of making this view.

-----------------

I am going to close this because I have completed v1 of this concept and this thread is getting way too long. Let's follow up with more specific issues targeting improvements to this product view.
