### ISSUE TITLE
color tag categories for Data & Products

### ISSUE THREAD

**Issue by bbest** [marinebon/www_marinebon2#43]
For instance, we could:

- [ ] Add legend with colors associated by category (region, org, tool, product type)
- [ ] Add Javascript to page, eg now https://marinebon2.netlify.app/product_viewer/

```javascript
$("[data-filter^='.js-id-region--']").
  css('background-color', 'blue');
$("[data-filter^='.js-id-org--']").
  css('background-color', 'green');
$("[data-filter^='.js-id-tool--']").
  css('background-color', 'red');
$("[data-filter^='.js-id-product_type--']").
  css('background-color', 'yellow');
```

![image](https://user-images.githubusercontent.com/2837257/150862342-78faddd9-4563-4912-b240-f27e3e6b9ea9.png)

**Comment by 7yl4r** [comment]
Took some trial and error but it is done!

**Comment by bbest** [comment]
So cool! The text is hard to read though with current color palette:

![image](https://user-images.githubusercontent.com/2837257/154143246-4c210f5a-7954-4cbc-b6eb-b711d1d4a2a2.png)

**Comment by MathewBiddle** [comment]
See this ticket too https://github.com/marinebon/www_marinebon2/issues/39#issuecomment-1036629379
